# Number of days of inactivity before an issue becomes stale
daysUntilStale: 365
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: expired
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as expired because it has not had
  recent activity. To prevent it from being closed, please leave a
  message. Consider giving the original message a thumbs up if this issue is
  important to you. Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
