macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  env:
    LEIN_ROOT: "true"
    GRAALVM_VERSION: "22.1.0"
    GRAALVM_HOME: ${HOME}/graalvm-ce-java11-22.1.0/Contents/Home
    CLJ_KONDO_PLATFORM: macos # used in release script
    CLJ_KONDO_ARCH: aarch64
    CLJ_KONDO_TEST_ENV: native
    GITHUB_TOKEN: ENCRYPTED[d6ff8cdc392157f211c754fa0763875434d1bfde0c00a05e48ba9470003a76c14c9213adb80623f81e13f2f0fa8fbd57]
  script: |
    sudo .circleci/script/install-clojure
    sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
    sudo .circleci/script/install-leiningen

    if ! [ -d graalvm-ce-java11-22.1.0 ]; then
      curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java11-darwin-amd64-22.1.0.tar.gz
      tar xzf graalvm-ce-java11-darwin-amd64-22.1.0.tar.gz
    fi

    export PATH=$GRAALVM_HOME/bin:$PATH
    java -version

    script/compile

    script/test

    VERSION=$(cat resources/CLJ_KONDO_VERSION)
    arch=${CLJ_KONDO_ARCH:-amd64}
    archive="clj-kondo-$VERSION-$CLJ_KONDO_PLATFORM-$arch.zip"
    zip "$archive" clj-kondo
    bb release-artifact "$archive" || true
  binaries_artifacts:
    path: "clj-kondo-*.zip"
